FROM tomcat:10.0

RUN rm -rf /usr/local/tomcat/webapps && mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps

ADD demo-2-java-ssl/localhost.p12 /usr/local/tomcat/conf/server.jks
ADD demo-2-java-ssl/server.xml /usr/local/tomcat/conf

EXPOSE 8443